api = "0.2"

[buildpack]
id = "neetodeploy/nodejs"
version = "0.5.14"
name = "Node.js"
homepage = "https://github.com/heroku/buildpacks-nodejs"

[[buildpack.licenses]]
type = "MIT"

[[order]]

[[order.group]]
id = "neetodeploy/nodejs-engine"
version = "0.8.16"

[[order.group]]
id = "neetodeploy/nodejs-corepack"
version = "0.1.2"
optional = true

[[order.group]]
id = "neetodeploy/nodejs-yarn"
version = "0.3.3"


[[order]]

[[order.group]]
id = "neetodeploy/nodejs-engine"
version = "0.8.16"

[[order.group]]
id = "neetodeploy/nodejs-npm"
version = "0.5.3"

[metadata]
[metadata.release]
[metadata.release.docker]
repository = "public.ecr.aws/heroku-buildpacks/heroku-nodejs-buildpack"
