api = "0.2"

[buildpack]
id = "neetodeploy/nodejs"
version = "0.5.14"
name = "Node.js"
homepage = "https://github.com/heroku/buildpacks-nodejs"

[[buildpack.licenses]]
type = "MIT"

[[order]]

[[order.group]]
id = "neetodeploy/nodejs-engine"
version = "0.8.15"

[[order.group]]
id = "neetodeploy/nodejs-corepack"
version = "0.1.1"
optional = true

[[order.group]]
id = "neetodeploy/nodejs-yarn"
version = "0.3.2"

[[order.group]]
id = "heroku/procfile"
version = "2.0.0"
optional = true

[[order]]

[[order.group]]
id = "neetodeploy/nodejs-engine"
version = "0.8.15"

[[order.group]]
id = "neetodeploy/nodejs-npm"
version = "0.5.2"

[[order.group]]
id = "heroku/procfile"
version = "2.0.0"
optional = true

[metadata]
[metadata.release]
[metadata.release.docker]
repository = "public.ecr.aws/heroku-buildpacks/heroku-nodejs-buildpack"
