api = "0.6"

[buildpack]
id = "neetodeploy/nodejs-test"
version = "0.0.0"
name = "Node.js"
homepage = "https://github.com/heroku/buildpacks-nodejs"

[[order]]

[[order.group]]
id = "neetodeploy/nodejs-engine"
version = "0.8.16"

[[order.group]]
id = "neetodeploy/nodejs-corepack"
version = "0.1.2"
optional = true

[[order.group]]
id = "neetodeploy/nodejs-yarn"
version = "0.3.3"

[[order.group]]
id = "heroku/procfile"
version = "2.0.0"
optional = true

[[order]]

[[order.group]]
id = "neetodeploy/nodejs-engine"
version = "0.8.16"

[[order.group]]
id = "neetodeploy/nodejs-npm"
version = "0.5.3"

[[order.group]]
id = "heroku/procfile"
version = "2.0.0"
optional = true
